### ISSUE TITLE
User should be able to specify --charset, because not all files are utf-8

### ISSUE THREAD

**Issue by fool2fish** [fishbar/jscoverage#10]
As captioned.

The default value of --charset is utf-8.

Just a little modification.

file: lib/index.js line:105

`content = fs.readFileSync(source).toString();`  => `content = fs.readFileSync(source).toString(charset);`

**Comment by fishbar** [comment]
~~ 检查文件写入编码中。。。~~

反悔了，gbk的文件，还是人肉utf-8吧，-_-!
