### ISSUE TITLE
Incorrectly reporting 90% coverage

### ISSUE THREAD

**Issue by erunion** [fishbar/jscoverage#15]
So I've got a small wrapper for [bcrypt](https://npmjs.org/package/bcrypt), a corresponding test, and after running it through Mocha and jscoverage, it's returning 90% coverage. It's got 100% coverage, however.

![2013-10-16 at 2 39 pm](https://f.cloud.github.com/assets/33762/1347115/819b404a-36ab-11e3-9e13-56209f244066.png)

**_bcrypt.js**_

<pre>
'use strict';

var bcrypt = require('bcrypt');

exports.saltAndHash = function (plaintext, callback) {
    bcrypt.genSalt(function (err, salt) {
        if (err) {
            return callback(err);
        }

        bcrypt.hash(plaintext, salt, function (err, hash) {
            if (err) {
                return callback(err);
            }

            return callback(null, hash);
        });
    });
};

exports.compare = bcrypt.compare;
</pre>

**_test/bcrypt.js**_

<pre>
'use strict';

var bootstrap = require(__dirname + '/../../bootstrap'),
    expect = require('chai').expect,
    should = require('chai').should(),
    bcrypt = require(bootstrap.dir.app + '/lib/bcrypt'),
    proxyquire = require('proxyquire'),
    stub = null;

describe('Bcrypt', function () {
    describe('.saltAndHash()', function () {
        it('should salt and hash a password without throwing an error', function (done) {
            bcrypt.saltAndHash('password', function (err, hash) {
                expect(err).to.equal(null);
                hash.should.be.a('string');
                done();
            });
        });

        describe('.genSalt()', function () {
            it('should throw an error to a callback', function (done) {
                stub = proxyquire(bootstrap.dir.app + '/lib/bcrypt', {
                    'bcrypt': {
                        genSalt: function (callback) {
                            return callback(true);
                        }
                    }
                });

                stub.saltAndHash('password', function (err, hash) {
                    expect(err).to.equal(true);
                });

                done();
            });
        });

        describe('.hash()', function () {
            it('should throw an error to a callback', function (done) {
                stub = proxyquire(bootstrap.dir.app + '/lib/bcrypt', {
                    'bcrypt': {
                        genSalt: function (callback) {
                            return callback(false, 'fakeSalt');
                        },
                        hash: function (plaintext, salt, callback) {
                            return callback(true);
                        }
                    }
                });

                stub.saltAndHash('password', function (err, hahs) {
                    expect(err).to.equal(true);
                });

                done();
            });

            it('should return a hashed password and no error', function (done) {
                bcrypt.saltAndHash('password', function (err, hash) {
                    expect(err).to.equal(null);
                    hash.should.be.a('string');
                    done();
                });
            });
        });
    });

    describe('.compare()', function () {
        var hash = '$2a$10$rWMbTnzXoYgIm1tLpwjcEuhnLfLdazg6brgEYZFoebd83dzq4KrXu';

        it('should return true when comparing the same password', function (done) {
            bcrypt.compare('password', hash, function (err, response) {
                expect(response).to.be.true;
                done();
            });
        });

        it('should return false when comparing the a bad match', function (done) {
            bcrypt.compare('badpassword', hash, function (err, response) {
                expect(response).to.be.false;
                done();
            });
        });
    });
});
</pre>

**_Makefile**_

<pre>
test:
    mocha --reporter spec $(shell find test/app/ -name "*.js")

coverage: app-cov
    CODE_COVERAGE=1 mocha test --reporter html-cov $(shell find test/app/ -name "*.js") > coverage.html

app-cov: clean
    jscoverage app app-cov

clean:
    rm -rf app-cov

.PHONY: test
</pre>

Any ideas as to what's up?

**Comment by fishbar** [comment]
jscoverage upgrade to v0.5, try it again:

mocha -r jscoverage test/test.js

**Comment by erunion** [comment]
![2014-04-10 at 9 30 am](https://cloud.githubusercontent.com/assets/33762/2670422/8cff18ce-c0cd-11e3-8775-df9e75d2ff4d.png)

Nice job!
