### ISSUE TITLE
Please use tags when release new version

### ISSUE THREAD

**Issue by LeoIannacone** [fishbar/jscoverage#20]
Hello,

I'm from debian/ubuntu world. 

We would like to package your module, but we have some problem: our automatic system, which checks for new releases in github, looks for tags in the relative project homepage, but it seems you do not provide them (last one is v0.3.8.. no tag for 0.5.0-rc2 ).

Can you please consider to use tags when release a new version of your software?

This is really important for us.

**Comment by LeoIannacone** [comment]
Moreover 0.5.0-rc2 is greater than 0.5.0.

You should consider to use use "0.5.0~rc2" instead.

Thanks in advance.

Leo.

**Comment by fishbar** [comment]
got it, thanks
