### ISSUE TITLE
JsCoverage doesn't work on windows

### ISSUE THREAD

**Issue by uttamk** [fishbar/jscoverage#4]
When running jscoverage on windows it throws an error, saying 'abs source path or abs dest path needed!'. A closer look at index.js revealed that there is regex that checks if the path is absolute. line 74

var exp_abs = /^\//;

This assumes that the root starts with a /. This is not true for windows. Taking out the regex check fixes it on windows. I believe that the regex check is not needed, since on line 82-93, you check if it's a file or directory anyway. I have forked the repo for now. Is there any reason for the regex check. If not then should I submit a pull request ?

**Comment by fishbar** [comment]
looks like a bug,  i will fix it this weekend

**Comment by fishbar** [comment]
fixed
