### ISSUE TITLE
Double backslash issue on Windows

### ISSUE THREAD

**Issue by GiantKouKou** [fishbar/jscoverage#8]
Generated instrumented files are missing double backslash  in intialisation phase :

The following code is generated :

`_$jscoverage_init(_$jscoverage, "service\index.js",[7,8,9,10,11,12,14]);
 _$jscoverage_init(_$jscoverage_cond, "service\index.js",[]);
 _$jscoverage["service\index.js"].source = ["/**"..."];`

Instead of this one :

`_$jscoverage_init(_$jscoverage, "service\\index.js",[7,8,9,10,11,12,14]);
_$jscoverage_init(_$jscoverage_cond, "service\\index.js",[]);
_$jscoverage["service\\index.js"].source = ["/**"..."];`

In the rest of the code, double backslash are correctly generated :

`_$jscoverage_done("service\\index.js", 12);`

**Comment by gustavohenke** [comment]
I'd like to know about this too.
